### ISSUE TITLE
Hope to improve the temporary files path

### ISSUE THREAD

**Issue by Lawrence-Opensource** [AmusementClub/OKEGui#2]
The OKEGui products tooooo many temporal files under the source path. Hope to sort the cache files to some specified sub folders, such as ./00001.m2ts_01/00001.m2ts.hevc or ./cache_video/00001.m2ts.hevc.

**Comment by AkarinVS** [comment]
Please give the branch https://github.com/AkarinVS/OKEGui/tree/custom/readonly-source-dir a try.
If you want a binary release, see https://github.com/AkarinVS/OKEGui/actions?query=branch%3Acustom%2Freadonly-source-dir)

It's a very ugly hack though and I don't guarantee it will work under all circumstances.
(Also note, you will need to use my https://github.com/AkarinVS/L-SMASH-Works/releases/ to fully avoid any writes to the source directory.)

Note that this branch also integrates the `OKE:SCRIPTDIR` feature.

**Comment by AkarinVS** [comment]
The fix is included in my release https://github.com/AkarinVS/OKEGui/releases/tag/v7.2.1

**Comment by AkarinVS** [comment]
[v7.2.6](https://github.com/AmusementClub/OKEGui/releases/tag/v7.2.6) is probably the most polished solution so far.
It has:
- separate working directory and output directory, intermediate files are no longer saved to source BDMV directories, enabling the use of readonly BDMV source
  - when uploading encoded results, you no longer need to filter though all those intermediate files, and can just upload the final mkv/mka from the output directory
- configurable stripping of commonly used path components (like "BDMV", "STREAM") in working & output directory paths
